apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  storageClassName: development
  awsElasticBlockStore:
    volumeID: vol-0ab2ba888bd7c6521
    fsType: ext4
