apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  name: example-{{ .Release.Name }}
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: example-{{ .Release.Name }}
          servicePort: 80
